name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
       
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push the backend
        uses: docker/build-push-action@v3
        with:
          context: ./server
          push: true
          tags: gerrome/MERN-Social-Media_server:1
       

      - name: Build and push the frontend
        uses: docker/build-push-action@v3
        with:
          context: ./client
          push: true
          tags: gerrome/MERN-Social-Media_client:1
